# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Temp\sleepDetectionGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1099, 805)
        MainWindow.setStyleSheet("background-color: rgb(81, 81, 81);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 10, 461, 60))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    color : rgb(217, 217, 217)\n"
"}")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(280, 620, 231, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.btn_start.setFont(font)
        self.btn_start.setAutoFillBackground(False)
        self.btn_start.setStyleSheet("QPushButton{\n"
"    border: 3px solid rgb(129, 129, 129);\n"
"    border-radius: 20px;\n"
"    color : rgb(59, 157, 90)\n"
"}")
        self.btn_start.setObjectName("btn_start")
        self.btn_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop.setGeometry(QtCore.QRect(610, 620, 231, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.btn_stop.setFont(font)
        self.btn_stop.setAutoFillBackground(False)
        self.btn_stop.setStyleSheet("QPushButton{\n"
"    border: 3px solid rgb(129, 129, 129);\n"
"    border-radius: 20px;\n"
"    color : rgb(213, 84, 91)\n"
"}")
        self.btn_stop.setObjectName("btn_stop")
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(240, 100, 641, 481))
        self.imageLabel.setStyleSheet("QLabel{\n"
"    border: 1px solid rgb(129, 129, 129);\n"
"    border-radius: 15px;\n"
"    color : rgb(217, 217, 217)\n"
"}")
        self.imageLabel.setText("")
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1099, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btn_start.clicked.connect(MainWindow.startchk) # type: ignore
        self.btn_stop.clicked.connect(MainWindow.stopchk) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:26pt;\">student sleep detector</span></p></body></html>"))
        self.btn_start.setText(_translate("MainWindow", "start analyzing"))
        self.btn_stop.setText(_translate("MainWindow", "stop analyzing"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
